import time
from contextlib import redirect_stdout
from io import StringIO
from pathlib import Path

import settings_doc
import settings_doc.main


def get_env_file_string(class_name: str) -> None:
    """Generate the environment file string for the given class name."""
    settings_doc.main.app(
        [
            "generate",
            "--class",
            class_name,
            "-f",
            "dotenv",
        ],
        standalone_mode=False,
    )


def print_title(title: str) -> None:
    """Print a title with a separator."""
    print(f"\n{'#' * 80}\n# {title}\n{'#' * 80}\n")


TIMESTAMP_LINE_INDEX = 4


def generate_env_example(target_file: Path | str | None = None) -> str:
    """Generate the environment file example.

    Args:
        target_file (Path | str | None, optional): The path to the target file. Defaults to None. \
            If None, the generated example will be only printed to stdout and not saved to a file.
    """
    result = StringIO()

    with redirect_stdout(result):
        print("# Auto-generated example environment file for Horde Model Reference")
        print("# This file is generated by the settings_doc package.")
        print("# Do not edit this file manually.")
        print()

        print(f"# Generated on (UTC): {time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime())}")
        print()

        print_title("Horde Model Reference Settings")
        get_env_file_string("horde_model_reference.HordeModelReferenceSettings")

        print_title("AI Horde Client+Worker Settings")
        get_env_file_string("haidra_core.ai_horde.settings.AIHordeWorkerSettings")

        print_title("Github Proxying Settings")
        get_env_file_string("horde_model_reference.GithubProxySettings")

        print_title("AI Horde CI Settings")
        get_env_file_string("haidra_core.ai_horde.meta.AIHordeCISettings")

    result_string = result.getvalue()

    timestamp_line = result_string.splitlines()[TIMESTAMP_LINE_INDEX]

    if not timestamp_line.startswith("# Generated on (UTC):"):
        raise ValueError("Timestamp line is missing, on wrong line, or malformed.")

    if target_file:
        with open(target_file, "w") as f:
            f.write(result_string)

    return result_string


if __name__ == "__main__":
    target_file = Path(__file__).parent.parent / ".env.example"
    print(generate_env_example(target_file))
